### PR TITLE
Fix MyRocks compile warnings-treated-as-errors on Fedora 30, gcc 9.1.1 (#5553)

### LINKED ISSUE #66: Cherry pick to build with gcc 9
Hello,

It would be nice if you could cherry pick that.

https://github.com/facebook/rocksdb/pull/5553

### PR DESCRIPTION
**Pull request by andreimatei**
Fixes #66

This is a cherry-pick from Facebook's master.

Summary:
- Provide assignment operator in CompactionStats
- Provide a copy constructor for FileDescriptor
- Remove std::move from "return std::move(t)" in BoundedQueue
Pull Request resolved: https://github.com/facebook/rocksdb/pull/5553

Differential Revision: D16230170

fbshipit-source-id: fd7c6e52390b2db1be24141e25649cf62424d078

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/rocksdb/69)

### CODE REVIEW

File: db/internal_stats.h [hunk 1]
```diff
@@ -237,6 +237,28 @@ class InternalStats {
...
+      num_input_records = c.num_input_records;
+      num_dropped_records = c.num_dropped_records;
+      count = c.count;
+
+      int num_of_reasons = static_cast<int>(CompactionReason::kNumOfReasons);
+      for (int i = 0; i < num_of_reasons; i++) {
+        counts[i] = c.counts[i];
+      }
+      return *this;
+    }
```
Comment (petermattis) [inline db/internal_stats.h:260]: Pretty sure that they could have either avoided the duplication here or in the copy constructor. I've forgotten the syntax for doing so, but because this is already upstream it doesn't matter too much.

**Review by petermattis — APPROVED** [review]
LGTM

Can you also indicate this fixes https://github.com/cockroachdb/rocksdb/issues/66?

File: db/internal_stats.h (hunk 1 above)
Comment (andreimatei) [reply db/internal_stats.h:260]: I'm not sure why they didn't just say `CompactionStats& operator=(const CompactionStats& c) = default;`. But then again, I don't know these things any more.

**Review by andreimatei — COMMENTED** [review]
> Can you also indicate this fixes #66?

It's in the commit message.

File: db/internal_stats.h (hunk 1 above)
Comment (ajkr) [reply db/internal_stats.h:260]: `counts` requires a deep copy which wouldn't happen with the default constructor.

To avoid duplication the copy constructor should call the assignment operator like `*this = other;`.
